### ISSUE TITLE
The services use neo4j embedded. Change it to connect to graphenedb.

### ISSUE THREAD

**Issue by mateusf777** [SimpleApplicationsOrg/skillTests#3]

**Comment by albertoperdomo** [comment]
Hello! :)

I'm one of the founders at GrapheneDB. Please let us know if you need help with this.
Happy to support you! ;)

![](http://i.gifly.com//media_gifly/y/9/k/C/b/y9kCrUD_c48eda.gif)

**Comment by mateusf777** [comment]
Thank you for the support @albertoperdomo, I will contact you as soon as I need!
